//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class myContact
    {
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public int contactID { get; set; }
    }
}
